name: rt-conf
base: core24
version: '0.1'
summary: Configure and tune your real-time system
description: |
  Tool destined to configure real-time parameters in a Linux system.
  Currently let's you configure kernel commandline parameters.

grade: stable
confinement: strict

parts:
  src:
    source: .
    plugin: go
    build-snaps:
      - go

apps:
  rt-conf:
    command: bin/rt-conf
