name: rt-conf
base: core24
version: '0.1'
summary: Configure and tune your real-time system
description: |
  Tool destined to configure real-time parameters in a Linux system.
  Currently let's you configure kernel commandline parameters.

grade: stable
confinement: strict

parts:
  src:
    source: .
    plugin: go
    build-snaps:
      - go

  config:
    plugin: dump
    source: .
    stage:
      - config.yaml

plugs:
  etc-default-grub:
    interface: system-files
    write:
      - /etc/default/grub

  proc-device-tree-model:
    interface: system-files
    read:
      - /proc/device-tree/model

  # NOTE: this needs to go away once
  # https://github.com/canonical/snapd/pull/14881 is released to snapd
  sys-kernel-irq:
    interface: system-files
    read:
      - /sys/kernel/irq

  # NOTE: this needs to go away once
  # https://github.com/canonical/snapd/pull/14424 is released to snapd
  proc-irq:
    interface: system-files
    write:
      - /proc/irq

apps:
  rt-conf: &rt-conf
    plugs:
      - home
      - etc-default-grub
      - proc-device-tree-model
      - hardware-observe
      - sys-kernel-irq # NOTE: this needs to go away
      - proc-irq # NOTE: this needs to go away
      # - cpu-control # NOTE: this will replace `sys-kernel-irq` and `proc-irq`
    command: bin/rt-conf
    environment:
      COMMON_CONFIG_PATH: $SNAP_COMMON/config.yaml

  rt-confd:
    <<: *rt-conf
    daemon: oneshot
    install-mode: enable
