name: rt-conf
base: core24
version: nil
summary: Configure and tune your real-time system
description: |
  Tool destined to configure real-time parameters in a Linux system.
  Currently let's you configure kernel commandline parameters.

grade: stable
confinement: strict

parts:
  local:
    source: snap/local
    plugin: dump

  rt-conf:
    source: .
    plugin: go
    build-snaps:
      - go
    override-build: |
      craftctl set version=0.1+$(git describe --always --dirty)

  config-file:
    plugin: dump
    source: .
    stage:
      - config.yaml

plugs:
  # For reading config file from user home directory as root
  home:
    read: all

  etc-default-grub:
    interface: system-files
    write:
      - /etc/default/grub

apps:
  rt-conf: &rt-conf
    plugs:
      - home
      - etc-default-grub
      - hardware-observe
      - snapd-control
      - cpu-control
    command: bin/rt-conf

  rt-confd:
    <<: *rt-conf
    daemon: oneshot
    command: bin/rt-confd
