name: rt-conf
base: core24
version: '0.1'
summary: Configure and tune your real-time system
description: |
  Tool destined to configure real-time parameters in a Linux system.
  Currently let's you configure kernel commandline parameters.

grade: stable
confinement: strict

parts:
  local: 
    source: snap/local
    plugin: dump
    
  rt-conf:
    source: .
    plugin: go
    build-snaps:
      - go

  config-file:
    plugin: dump
    source: .
    stage:
      - config.yaml

plugs:
  etc-default-grub:
    interface: system-files
    write:
      - /etc/default/grub

  proc-device-tree-model:
    interface: system-files
    read:
      - /proc/device-tree/model

  # NOTE: see https://github.com/canonical/rt-conf/issues/23
  sys-kernel-irq:
    interface: system-files
    read:
      - /sys/kernel/irq

  # NOTE: see https://github.com/canonical/rt-conf/issues/23
  proc-irq:
    interface: system-files
    write:
      - /proc/irq

apps:
  rt-conf: &rt-conf
    plugs:
      - home
      - etc-default-grub
      - proc-device-tree-model
      - hardware-observe
      - sys-kernel-irq
      - proc-irq
      - snapd-control
      # - cpu-control # NOTE: this will replace `sys-kernel-irq` and `proc-irq`
    command: bin/rt-conf

  rt-confd:
    <<: *rt-conf
    daemon: oneshot
    command-chain:
      - bin/load-snap-options
    command: bin/rt-conf --file $CONFIG_FILE
