name: Test and Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  test-go:
    runs-on: ubuntu-latest
    name: Go Test

    steps:
      - uses: actions/checkout@v5
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.x'
      
      - name: Test
        run: go test ./...

  build:
    runs-on:  ubuntu-latest
    outputs:
      snap: ${{ steps.snapcraft.outputs.snap }}
    needs: [test-go]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build Snap
        uses: snapcore/action-build@v1
        id: snapcraft

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.snapcraft.outputs.snap }}
          path: ${{ steps.snapcraft.outputs.snap }}
          if-no-files-found: error
