#!/bin/bash -e

# Put the default configuration in place
cp "$SNAP"/config.yaml "$DEFAULT_CONFIG_FILE"

# Set the default config
snapctl set config-file="$DEFAULT_CONFIG_FILE" \
            verbose=false

